### ISSUE TITLE
IP8: Show documentation in per listbox cell help entries

### ISSUE THREAD

**Issue by t-b** [byte-physics/igor-code-browser#11]
We can also nicely format the documentation using basic HTML, https://doc.qt.io/qt-5/richtext-html-subset.html.

**Comment by t-b** [comment]
There is an igor function/operation to get the `n` comment lines above a function. So there should not be the need to do any manual docu fetching. Function comments are enough for now.

**Comment by ukos-git** [comment]
nice. thanks for the hint.

**Comment by ukos-git** [comment]
from `displayhelptopic("ProcedureText")`

> Setting linesOfContext  to -n , where n >1, returns at most n  lines before the procedure that are not part of the preceding macro or function. Blank lines are not omitted in this case. n can be -inf, which acts the same as -1 but includes blank lines.

**Comment by ukos-git** [comment]
#23 already has a Function to get text from a specified function. Need to store that in a separate column of declWave.

**Comment by ukos-git** [comment]
ok. I'm giving up.

* First of all, IgorPro 8 outputs the whole function in addition to the Comment-Lines above the function. This is undescribed behavior but I can live with that.

* Second: The RegExp parsing does not match with what I get from https://regex101.com I have tried every possible way for the following pattern but I can not get it to extract the comments correctly.

```regexp
^(?is)(.*)^(\/\/.*)Function((?s:.*))End
```

seems like `$` is not allowed inside the string (D flag) and I also think that the same goes for `^`.

simple example to match is 

```igorpro
#pragma TextEncoding = "UTF-8"
#pragma rtGlobals=3		// Use modern global access method and strict wave access.

#include "MIES_include"

// this is a comment
// this is the 2nd line comment
function test()
End
```

I pushed the current WIP state to https://github.com/byte-physics/igor-code-browser/pull/25 (which also outputs preceding non-comment lines and has `//` not stripped from the tooltip.

@t-b Can you help me matching only the comment part in this procedure?

**Comment by t-b** [comment]
@ukos-git Sure! Multiline regexps are the devil!! You missed using the (?m) modifier explained in DisplayHelpTopic "Match Option Settings".

But to avoid that issue altogether I pushed something using GrepList. This assumes that EOL is already normalized to \r.
